modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"
issueTrackerURL = "https://github.com/Juuxel/Adorn/issues"

[[mods]]
modId = "adorn"
version = "${version}"
displayName = "Adorn"
description = "Decorate your home!"
authors = "Juuz"
logoFile = "icon.png"

[[dependencies.adorn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"

[[dependencies.adorn]]
modId = "forge"
mandatory = true
versionRange="[41.0.38,)"
