{
  "name": "Bug report",
  "description": "Report a bug or a crash",
  "labels": ["bug"],
  "body": [
    {
      "type": "input",
      "id": "adorn_version",
      "attributes": {
        "label": "Adorn version",
        "description": "Make sure that you're running the latest version. Your bug may have been fixed already!"
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "input",
      "id": "minecraft_version",
      "attributes": {
        "label": "Minecraft version"
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "dropdown",
      "id": "loader",
      "attributes": {
        "label": "Mod loader",
        "options": [
          "Fabric",
          "Forge",
          "Quilt"
        ]
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "input",
      "id": "loader_version",
      "attributes": {
        "label": "Mod loader version",
        "description": "On Fabric: both Fabric Loader and Fabric API\nOn Quilt: both Quilt Loader and QFAPI"
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "textarea",
      "id": "describe",
      "attributes": {
        "label": "Describe the bug",
        "description": "A clear and concise description of what the bug is and what you expected to happen. You can include images!"
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "textarea",
      "id": "reproduction",
      "attributes": {
        "label": "To reproduce",
        "description": "Steps to reproduce the bug or crash."
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "textarea",
      "id": "logs",
      "attributes": {
        "label": "Game logs",
        "description": "**If your bug is a crash, attach the full game log here.** It can be found in `logs/latest.log` after the game crashes.\nIf the log is long, you can also upload it on GitHub Gist and paste the link here.",
        "render": "text"
      },
      "validations": {
        "required": false
      }
    },
    {
      "type": "textarea",
      "id": "extra",
      "attributes": {
        "label": "Additional context",
        "description": "If you have anything else to add, please say it here."
      },
      "validations": {
        "required": false
      }
    },
    {
      "type": "markdown",
      "attributes": {
        "value": "Thanks for taking the time to fill out this bug report!"
      }
    }
  ]
}
